# Generated by Django 2.2.5 on 2019-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('title', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('num_votes', models.IntegerField()),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField(null=True)),
                ('weighted_rating', models.FloatField()),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('summary', models.TextField()),
                ('country', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
